export const productionReadiness = {
  ticket: 'COUR-112',
  title: 'Déployer et valider la version de production du site Coursia',
  requiredEnvironmentVariables: [
    'NUXT_PUBLIC_SITE_URL',
    'NUXT_PUBLIC_SUPABASE_URL',
    'NUXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
    'NUXT_SUPABASE_SERVICE_ROLE_KEY',
    'NUXT_SENTRY_ENVIRONMENT',
    'NUXT_SENTRY_RELEASE',
    'NUXT_SENTRY_SOURCEMAPS',
    'NUXT_PUBLIC_SENTRY_ENVIRONMENT',
    'NUXT_PUBLIC_SENTRY_RELEASE',
  ],
  publicValidationRoutes: [
    '/',
    '/robots.txt',
    '/sitemap.xml',
    '/fonctionnalites',
    '/comment-ca-marche',
    '/tarifs',
    '/faq',
    '/contact',
    '/liste-attente',
    '/legal',
    '/support',
  ],
  adminValidationChecks: [
    '/admin redirige les visiteurs non authentifiés vers /auth/login',
    'un compte autorisé peut ouvrir /admin après connexion',
    'les données affichées restent limitées au rôle actif',
    'la création, prévisualisation et publication d’une recette complète sont testées',
  ],
  supabaseMigrationChecks: [
    'supabase migration list est comparé entre local, preview et production',
    'les migrations sont appliquées en preview avant production',
    'une sauvegarde ou un point de restauration est confirmé avant production',
    'les advisors Supabase et contrôles RLS/Storage sont relus avant promotion',
    'aucune migration destructive n’est appliquée sans plan de retour écrit',
  ],
  rollbackChecks: [
    'le dernier commit stable et son artifact sont identifiés',
    'les variables de production sont conservées hors Git dans le secret store',
    'le rollback applicatif consiste à redéployer le dernier commit stable',
    'le rollback base utilise une migration corrective ou une restauration validée',
    'les responsabilités release, Supabase, support et décision rollback sont nommées',
  ],
  blockingBugCriteria: [
    'aucun bug P0/P1 ouvert sur authentification, admin, publication ou paiement',
    'aucune clé privilégiée dans le bundle client',
    'aucun bypass admin E2E actif en production',
    'aucune vulnérabilité critique npm connue non acceptée',
    'les findings sécurité COUR-109 sont corrigés ou explicitement acceptés avant go-live',
  ],
} as const
